### ISSUE TITLE
make a .txt file

### ISSUE THREAD

**Issue by csdinos** [csdinos/git-init-team#8]
@JohnGeorgiadis @ntsounosp

**Comment by john-d-pelingo** [comment]
CUTIIIIIIIIIIIIIIIIEEEEEEEEEEEEEEEee

**Comment by ntsparis** [comment]
hey :dart:

**Comment by john-d-pelingo** [comment]
SUP

**Comment by csdinos** [comment]
work or im gonna get you fired gentlemen

**Comment by john-d-pelingo** [comment]
PLEASE

**Comment by ntsparis** [comment]
wow take it easy man, lets eat some pizza! @john-d-pelingo  lets go now!

**Comment by JohnGeorgiadis** [comment]
Teleiwsate
